### ISSUE TITLE
TypeError: Cannot read property 'replay' of null

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/manastorm#99]
https://sentry.io/zero-to-heroes/manastorm/issues/352894537/

```
TypeError: Cannot read property 'replay' of null
  at b.moveToStart (/scripts/plugins.52e0fbf8.js:2:22785)
  at HTMLUnknownElement.d (/scripts/plugins.52e0fbf8.js:15:4766)
  at Object.e.invokeGuardedCallback (/scripts/plugins.52e0fbf8.js:21:5894)
  at g (/scripts/plugins.52e0fbf8.js:18:8641)
  at Object.h [as executeDispatchesInOrder] (/scripts/plugins.52e0fbf8.js:18:8888)
...
(14 additional frame(s) were not displayed)
```

**Comment by sebastientromp** [comment]
Reproduced systematically in prod, not in dev. Let's see if this occurs again after the next version load

**Comment by sebastientromp** [comment]
Still occurs in prod
